### ISSUE TITLE
Lloid doesn't respond to invalid commands

### ISSUE THREAD

**Issue by cmarguel** [cmarguel/lloid#23]
Lloid will respond with usage statements if you use existing commands incorrectly, such as `!host` via DM/channel, or `host` via DM, without arguments.

However, Lloid will not respond to gibberish, or commands that do not exist. `asdf` and `!asdf` do nothing on either channel.

**Comment by WesselKuipers** [comment]
It turns out that `@host.error` gets called on with a `commands.CheckFailure` error if it fails `check_cog`, so that has to be manually checked for within the host error handler command.

The fact that the bot isn't  responding to non-existent commands is intended behaviour, this can be modified in `on_command_error()` for the entire bot, or `@{command}.error` for specific commands.

**Comment by cmarguel** [comment]
Resolved in https://github.com/cmarguel/lloid/commit/a8cba970b522e184a4d2308784c8fa5dea2b2cb5
